### ISSUE TITLE
Build Fails du to wrong OpenCV path

### ISSUE THREAD

**Issue by jhbruhn** [ros-melodic-arch/ros-melodic-depthimage-to-laserscan#1]
I'm having multiple problems:
1) This version is pretty outdated, maybe my second problem can be fixed by upgraded to the latest version
2) The build fails because the package relies on a path to an old opencv version (4.2.0, but the version on my system is 4.3.0):
```
scanning dependencies of target DepthImageToLaserScan
[ 11%] Building CXX object CMakeFiles/DepthImageToLaserScan.dir/src/DepthImageToLaserScan.cpp.o
make[2]: *** Keine Regel vorhanden, um das Ziel „/usr/lib/libopencv_calib3d.so.4.2.0“,
  benötigt von „devel/lib/libDepthImageToLaserScan.so“, zu erstellen.  Schluss.
make[1]: *** [CMakeFiles/Makefile2:298: CMakeFiles/DepthImageToLaserScan.dir/all] Fehler 2
make: *** [Makefile:150: all] Fehler 2
```

**Comment by jhbruhn** [comment]
Fixed by rebuilding `ros-melodic-image-geometry` for after an OpenCV update.

**Comment by bionade24** [comment]
The version is up to date, 2.x is ROS2.
